### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by matheusmota** [harena-lab/harena-manager#10]
### Project design
- [x]  Unified login. _Fagner: The route `/auth/login` indicates authentication only for authors. What about having a unified login for both (authors and players) with a rout `/user/login`._
- [ ]  Admin user vs. regular user. _Fagner: I need more information about this point in the next meeting._
- [x]  Adopt template and database instead of filesystem. _Fagner: I kept the filesystem in order to fast delivery, once I didn't know about all the logic under the CaseNotebook. In the last meeting with Andre, we agree with leave behind the filesystem. Now, I am updating everything to deal only with database._
---

#### /auth
- [x]  Login / jwt token provision
- [x]  Migrate user creation/register to `/user` instead of `/auth`
- [x] Use lucid auto relationship instead of manual query within the controllers

#### /user
- [x]  Register new user
- [x]  List user profiles
- [x]  Get user profile
- [x]  Update user profile
- [x]  Delete user profile
  - [x]  Review return status for deletion  (204 is ok, but 200/202 with json is better )
- [x]  List user cases
- [x]  List user executions
- [x]  List user executions per case - Fagner

#### /case
- [x]  List cases
  - [ ]  List cases should return cases which the user has access (publishing_flag)
  - [ ]  Flag for filtering self-created cases 
- [x]  Register new case
  - [x]  Review resource name: we should not adopt plural (/case~~s~~)
  - [ ]  Why "versionfile"? - _Fagner: I followed the same logic used by Andre, in CaseNtebook. As I understood, each case has many versions in which the first version would be returned by the Save New Case method_
  - [ ] Add support for publishing_flag - _Fagner: I didn't understand the whole point about publishing\_flag. I considered we will discuss this in the next meeting._

**Comment by matheusmota** [comment]
@faguim feel free to update the roadmap (add or check items) based on, for instance, PR #11
